### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by threadedblue** [abhinavmehndiratta/abhinavmehndiratta.github.io#1]
I get a build error with Julia 1.2

These are the commands:
pkg> add SuiteSparseGraphBLAS
pkg> build SuiteSparseGraphBLAS  

The error:
Building SuiteSparseGraphBLAS → `~/.julia/packages/SuiteSparseGraphBLAS/jdY9R/deps/build.log`
┌ Error: Error building `SuiteSparseGraphBLAS`: 
│ ERROR: LoadError: MethodError: no method matching iterate(::Nothing)
│ Closest candidates are:
│   iterate(!Matched::Core.SimpleVector) at essentials.jl:604
│   iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:604
│   iterate(!Matched::ExponentialBackOff) at error.jl:214
│   ...
│ Stacktrace:
│  [1] indexed_iterate(::Nothing, ::Int64) at ./tuple.jl:66
│  [2] top-level scope at /Users/geoffryroberts/.julia/packages/SuiteSparseGraphBLAS/jdY9R/deps/build.jl:18
│  [3] include at ./boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1094
│  [5] include(::Module, ::String) at ./Base.jl:31
│  [6] include(::String) at ./client.jl:431
│  [7] top-level scope at none:5
│ in expression starting at /Users/geoffryroberts/.julia/packages/SuiteSparseGraphBLAS/jdY9R/deps/build.jl:16
└ @ Pkg.Operations /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647

**Comment by abhinavmehndiratta** [comment]
Sorry, I was never notified of the issue. This is the repo for my website, the actual repo is https://github.com/abhinavmehndiratta/SuiteSparseGraphBLAS.jl, you should open an issue there. Anyway, the problem seems to be that you're using MacOS. Currently, the package only has builds for linux, but it'll support mac really soon.

**Comment by abhinavmehndiratta** [comment]
This is resolved by https://github.com/abhinavmehndiratta/SuiteSparseGraphBLAS.jl/pull/12 . We now have binaries for OSX. Closing this.
